# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6c1e4970b948e59872c6b4395c83ea24647e186257f183282f7bb243d3868cb90e070af02f5c1525a77693bf3699f6765985bbab0652b7b50076e7d8284110e

test:
  secret_key_base: cf891daeb765acd656f84e7a7bf67b117d241500fcb7a1e5925a4e2cd412e878be2ca3fa8627fa5ad430530fff91e125ac11a8f199cd19d42b3619a8ceb60bf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
